version: "3.8"
services:
  prometheus:
    image: prom/prometheus
    ports:
      - "0.0.0.0:9090:9090"
    networks:
      - lavih
    volumes:
      - prometheus:/etc/prometheus
  graphite:
    image: hopsoft/graphite-statsd
    ports:
      - "0.0.0.0:80:80"
      - "0.0.0.0:81:81"
      - "0.0.0.0:2003-2004:2003-2004"
      - "0.0.0.0:2023-2024:2023-2024"
      - "0.0.0.0:8125:8125"
      - "0.0.0.0:8126:8126"
    networks:
      - lavih
networks:
  lavih:
volumes:
  prometheus:
